### ISSUE TITLE
Deepl is offering a free development api, put an option to use in API.

### ISSUE THREAD

**Issue by TheFive** [gillescoolen/deepl-client#26]
https://www.deepl.com/pro#developer

**Comment by gillescoolen** [comment]
Will do!

**Comment by gillescoolen** [comment]
@TheFive Does your free key end with `:fx`?

**Comment by gillescoolen** [comment]
I've made [this pull request](https://github.com/gillescoolen/deepl-client/pulls) containing support for the free API key. I am having an issue where `tsc` is ignoring my `skipLibCheck`, which I will get sorted tomorrow or on Thursday. 

Afterwards I'll deploy a beta version, so you can test if it works for you. Sorry for the delay!
